site_name: EducaMinas

repo_url: https://github.com/unb-mds/EducaMinas-2024.1

nav:
  - Início: index.md
  - Sprints:
    - Sprint 0: sprints/sprint-0.md
    - Sprint 1: sprints/sprint-1.md
    - Sprint 2: sprints/sprint-2.md
    - Sprint 3: sprints/sprint-3.md
    - Sprint 4: sprints/sprint-4.md
    - Sprint 5: sprints/sprint-5.md
    - Sprint 6: sprints/sprint-6.md
    - Sprint 7: sprints/sprint-7.md
    - Sprint 8: sprints/sprint-8.md
    - Sprint 9: sprints/sprint-9.md
    - Sprint 10: sprints/sprint-10.md
    - Sprint 11: sprints/sprint-11.md
    - Sprint 12: sprints/sprint-12.md
    - Sprint 13: sprints/sprint-13.md
    - Sprint 14: sprints/sprint-14.md


  - Projeto:
    - Personas: project/personas.md
    - Story Map: project/storymap.md
    - Requisitos: project/requirements.md
    - EAP: project/eap.md
    - API: project/servicos.md
    - Arquitetura e Tecnologias: project/arquitetura.md
    - Protótipo: project/prototipo.md


  - Como contribuir:
    - Ambiente de desenvolvimento: environment.md
    - Primeiros passos - FRONTEND: contributing-frontend.md
    - Primeiros passos - BACKEND: contributing-backend.md

  - Sobre: about.md


theme:
  font:
    text: Open Sans
  language: pt-BR
  favicon: assets/logo.png
  logo: assets/logo.png
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - navigation.top
    - content.tabs.link


  palette:
    scheme: default
    accent: indigo
    primary: pink

  icon:
    repo: fontawesome/brands/github

extra:
  generator: false
