site_name: Docs-Educa Minas

repo_url: https://github.com/unb-mds/EducaMinas-2024.1

nav:
  - Home: index.md
  - Sprints: 
    - sprint 0: sprints/sprint-0.md 
    - sprint 1: sprints/sprint-1.md 
  - Sobre: about.md


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

  palette:
    scheme: "slate"
    primary: "purple"
    accent: "deep purple"

  icon:
    repo: fontawesome/brands/github
