site_name: Educa Minas

repo_url: https://github.com/unb-mds/EducaMinas-2024.1

nav:
  - Início: index.md
  - Sprints: 
    - Sprint 0: sprints/sprint-0.md 
    - Sprint 1: sprints/sprint-1.md 
    - Sprint 2: sprints/sprint-2.md
    - Sprint 3: sprints/sprint-3.md
    - Sprint 4: sprints/sprint-4.md
    - Sprint 5: sprints/sprint-5.md
    - Sprint 6: sprints/sprint-6.md
    - Sprint 7: sprints/sprint-7.md
    - Sprint 8: sprints/sprint-8.md

  - Projeto:
    - Personas: project/personas.md
    - Story Map: project/storymap.md
    - Requisitos: project/requirements.md
    - EAP: project/eap.md
    - Arquitetura: project/arquitetura.md
    - Protótipo: project/prototipo.md


  - Como contribuir: 
    - Primeiros passos: contributing.md
    - Ambiente de desenvolvimento: environment.md
    - Templates:
      - Issues template: template/issuetemplate.md
      - Pull Requests template: template/prTemplate.md
 
  - Sobre: about.md


theme:
  font:
    text: Open Sans
  language: pt-BR
  favicon: assets/logo.png
  logo: assets/logo.png
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate 
    - navigation.top
    - content.tabs.link


  palette:
    scheme: default
    accent: deep orange
    primary: pink

  icon:
    repo: fontawesome/brands/github

extra:
  generator: false
