site_name: Educa Minas

repo_url: https://github.com/unb-mds/EducaMinas-2024.1

nav:
  - Home: index.md
  - Sprints: 
    - sprint 0: sprints/sprint-0.md 
    - sprint 1: sprints/sprint-1.md 
    - sprint 2: sprints/sprint-2.md
    - sprint 3: sprints/sprint-3.md

  - Projeto:
    - Personas:
      - Lucas Silva: project/personaLucas.md
      - Fernanda Almeida: project/personaFernanda.md

  - Templates:
    - Issue template: templates/issuetemplate.md 

  - Sobre: about.md


theme:
  favicon: assets/logo.png
  logo: assets/logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

  palette:
    scheme: "slate"
    primary: "red"

  icon:
    repo: fontawesome/brands/github

    